
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: estudo-php
    volumes:
      - .:/var/www
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    container_name: estudo-nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    image: mysql:5.7
    container_name: estudo-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: estudo-phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql

  composer:
    image: composer:latest
    volumes:
      - ./:/app
    working_dir: /app

volumes:
  dbdata:


  
